#!/usr/bin/env python3
"""Build and validate the isolated NextPCB Phase 3H assembly exports.

The native KiCad position file is generated by the companion PowerShell
script. This helper creates the quote BOM, validates that both files describe
exactly the Phase 3H mounted population, and packages the position file in the
ZIP accepted by NextPCB. It does not modify the PCB or older manufacturing
manufacturing package.
"""

from __future__ import annotations

import csv
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile, ZipInfo


ROOT = Path(__file__).resolve().parents[1]
HW = ROOT / "hardware" / "kcan-bidirectional-pcb"
NEXTPCB = HW / "manufacturing" / "nextpcb"
BOM_SOURCE = HW / "BOM_PHASE3H.csv"
BOM_OUTPUT = NEXTPCB / "BMW-E9x-KCAN-Bidirectional-PCBA-BOM-NextPCB.csv"
POSITION_OUTPUT = NEXTPCB / "BMW-E9x-KCAN-Bidirectional-PCBA-Top.pos"
CENTROID_ZIP = NEXTPCB / "BMW-E9x-KCAN-Bidirectional-PCBA-Centroid-NextPCB.zip"

BOM_FIELDS = [
    "Designator",
    "Quantity",
    "Manufacturer Part Number",
    "Procurement Type",
    "Customer Note",
]
NO_SUBSTITUTION_NOTE = "Exact manufacturer part number required; no substitution."


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8-sig") as handle:
        reader = csv.DictReader(handle)
        if reader.fieldnames is None:
            raise ValueError(f"CSV without a header: {path}")
        return list(reader)


def mounted_rows() -> list[dict[str, str]]:
    rows = [row for row in read_csv(BOM_SOURCE) if row["assembly"] == "MOUNT"]
    if not rows:
        raise ValueError("Phase 3H BOM contains no mounted components")
    return rows


def split_references(value: str) -> list[str]:
    return [reference for reference in value.split() if reference]


def parse_kicad_position(path: Path) -> list[dict[str, str]]:
    placements: list[dict[str, str]] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
        if not line or line.startswith("#"):
            continue
        columns = line.split()
        if len(columns) != 7:
            raise ValueError(
                f"Unexpected KiCad position row at {path}:{line_number}: {line}"
            )
        placements.append(
            dict(zip(("Ref", "Val", "Package", "PosX", "PosY", "Rot", "Side"), columns))
        )
    return placements


def expected_references(rows: list[dict[str, str]]) -> set[str]:
    references: set[str] = set()
    for row in rows:
        row_references = split_references(row["reference"])
        if int(row["quantity"]) != len(row_references):
            raise ValueError(
                f"Per-board quantity mismatch for {row['reference']}: {row['quantity']}"
            )
        duplicate = references.intersection(row_references)
        if duplicate:
            raise ValueError(f"Duplicate mounted designator(s): {sorted(duplicate)}")
        references.update(row_references)
    return references


def write_nextpcb_bom(rows: list[dict[str, str]]) -> None:
    output_rows = []
    for row in rows:
        references = split_references(row["reference"])
        if not row["mpn"] or row["mpn"] in {"NONE", "PHYSICAL_GAP"}:
            raise ValueError(f"Mounted component without an exact MPN: {row['reference']}")
        output_rows.append(
            {
                "Designator": ", ".join(references),
                "Quantity": str(len(references)),
                "Manufacturer Part Number": row["mpn"],
                "Procurement Type": "",
                "Customer Note": NO_SUBSTITUTION_NOTE,
            }
        )

    NEXTPCB.mkdir(parents=True, exist_ok=True)
    with BOM_OUTPUT.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=BOM_FIELDS, lineterminator="\n")
        writer.writeheader()
        writer.writerows(output_rows)


def validate_position(rows: list[dict[str, str]]) -> None:
    placements = parse_kicad_position(POSITION_OUTPUT)
    references = [placement["Ref"] for placement in placements]
    if len(references) != len(set(references)):
        raise ValueError("NextPCB position file contains duplicate designators")

    expected = expected_references(rows)
    actual = set(references)
    if actual != expected:
        raise ValueError(
            "NextPCB position/BOM mismatch: "
            f"missing={sorted(expected - actual)}, extra={sorted(actual - expected)}"
        )
    invalid_sides = {
        placement["Ref"]: placement["Side"]
        for placement in placements
        if placement["Side"] != "top"
    }
    if invalid_sides:
        raise ValueError(f"NextPCB export must be Top-only: {invalid_sides}")


def build_centroid_zip() -> None:
    info = ZipInfo(POSITION_OUTPUT.name, date_time=(2026, 10, 4, 0, 0, 0))
    info.compress_type = ZIP_DEFLATED
    info.external_attr = 0o100644 << 16
    with ZipFile(CENTROID_ZIP, "w") as archive:
        archive.writestr(info, POSITION_OUTPUT.read_bytes())


def main() -> int:
    rows = mounted_rows()
    expected_references(rows)
    if not POSITION_OUTPUT.is_file():
        raise FileNotFoundError(
            f"Native KiCad position file is missing; run generate_phase3h_nextpcb.ps1: "
            f"{POSITION_OUTPUT}"
        )
    validate_position(rows)
    write_nextpcb_bom(rows)
    build_centroid_zip()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
